// frontend/src/App.tsx
import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
import { useCart } from './hooks/useCart';
import Home from './components/Home';
import ProductDetails from './components/ProductDetails';
import Cart from './components/Cart';
import './App.scss';

const App: React.FC = () => {
  const { cartCount } = useCart();
  const currentYear = new Date().getFullYear();

  return (
    <Router>
      <header className="header">
        <div className="logo">
          <Link to="/home">
            <img src="/assets/amavya-logo.png" alt="Amavya Logo" />
            <h1>AMAVYA</h1>
          </Link>
        </div>
        <nav className="menu">
          <a href="#home">Home</a>
          <a href="#products">Shop</a>
          <a href="#about">About</a>
          <a href="#contact">Contact</a>
          <Link to="/cart" className="cart-icon">
            🛒
            {cartCount > 0 && <span className="cart-badge">{cartCount}</span>}
          </Link>
        </nav>
      </header>

      <main className="main-content">
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/home" element={<Home />} />
          <Route path="/product/:id" element={<ProductDetails />} />
          <Route path="/cart" element={<Cart />} />
          <Route path="*" element={<Home />} />
        </Routes>
      </main>

      <footer className="footer" style={{ marginTop: '40px', padding: '20px', textAlign: 'center', backgroundColor: '#f5f5f5' }}>
        <p>&copy; {currentYear} Amavya. All rights reserved.</p>
      </footer>
    </Router>
  );
};

export default App;

// frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { CartService } from './services/cart.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  currentYear = new Date().getFullYear();
  cartCount = 0;

  constructor(private cartService: CartService) { }

  ngOnInit() {
    this.cartService.cartCount.subscribe(count => {
      this.cartCount = count;
    });
  }


}


<header class="header">
  <div class="logo">
    <img src="assets/amavya-logo.png" alt="Amavya Logo" />
    <h1>AMAVYA</h1>
  </div>
  <nav class="menu">
    <a href="#">Home</a>
    <a href="#products">Shop</a>
    <a href="#">About</a>
    <a href="#">Contact</a>
   <!--  <a routerLink="/cart" class="cart-link">
      🛒 Cart
    </a> -->
    <a routerLink="/cart" class="cart-icon">
      🛒
      <span class="cart-badge" *ngIf="cartCount > 0">{{ cartCount }}</span>
    </a>

  </nav>
</header>

<main class="main-content">
  <router-outlet></router-outlet>
</main>

<footer>
  <p>© 2025 Amavya. All rights reserved.</p>
</footer>
