// frontend/src/components/Home.tsx
import React, { useEffect } from 'react';
import { useApi } from '../hooks/useApi';
import { Product } from '../types/product.types';
import './Home.scss';
import { useNavigate } from 'react-router-dom';
import { useCart } from '../hooks/useCart';

const Home: React.FC = () => {
  const { products, getProducts, loading, error } = useApi();
  const { addToCart } = useCart();
  const navigate = useNavigate();

  useEffect(() => {
    getProducts();
  }, [getProducts]);

  const handleAddToCart = (product: Product, event: React.MouseEvent) => {
    event.stopPropagation();
    addToCart(product, 1);
    navigate('/cart');
  };

  if (loading) {
    return <div style={{ textAlign: 'center', padding: '2rem' }}>Loading products...</div>;
  }

  if (error) {
    return <div style={{ textAlign: 'center', padding: '2rem', color: 'red' }}>Error: {error}</div>;
  }

  return (
    <>
      <section className="hero">
        <div className="hero-content">
          <h2>Adorn Your Aura</h2>
          <p>Premium Anti-Tarnish Jewellery, Crafted for Everyday Elegance.</p>
          <a href="#products" className="btn">Explore Collection</a>
        </div>
      </section>

      <section className="categories">
        <h3>Shop by Category</h3>
        <div className="category-list">
          <button className="category active">All</button>
          <button className="category">Necklaces</button>
          <button className="category">Earrings</button>
          <button className="category">Bracelets</button>
          <button className="category">Bangles</button>
        </div>
      </section>

      <section id="products" className="product-section">
        <div className="product-container">
          {products && products.length > 0 ? (
            products.map((product) => (
              <div
                key={product.id}
                className="product-card"
                data-category={product.category}
                onClick={() => navigate(`/product/${product.id}`)}
              >
                <img
                  src={`/assets/prod-images/${product.thumbnail}`}
                  alt={product.name}
                />
                <h4>{product.name}</h4>
                <p className="price">₹{product.price}</p>

                <div className="card-actions">
                  <button
                    className="btn add-cart"
                    onClick={(e) => handleAddToCart(product, e)}
                  >
                    Add to Cart
                  </button>
                  <button className="btn buy-now">Buy Now</button>
                </div>
              </div>
            ))
          ) : (
            <p>No products available</p>
          )}
        </div>
      </section>
    </>
  );
};

export default Home;

// frontend/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../services/api.service';
import { Product } from '../models/product.model';
import { CartService } from '../services/cart.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent {
  currentYear = new Date().getFullYear();
  products: Product[] = [];

  constructor(private apiService: ApiService,
    private cartService: CartService) { }

  ngOnInit(): void {
    this.apiService.getProducts().subscribe(data => {
      this.products = data;
    });
  }

  /* addToCart(product: Product) {
    if (product) {
      this.cartService.addToCart(product, 1);
    }
  } */

  addToCart(product: Product, event: Event) {
    event.stopPropagation(); // VERY IMPORTANT — this stops routerLink navigation
    if (product) {
      this.cartService.addToCart(product, 1);
    }
  }

}

<section class="hero">
  <div class="hero-content">
    <h2>Adorn Your Aura</h2>
    <p>Premium Anti-Tarnish Jewellery, Crafted for Everyday Elegance.</p>
    <a href="#products" class="btn">Explore Collection</a>
  </div>
</section>

<section class="categories">
  <h3>Shop by Category</h3>
  <div class="category-list">
    <button class="category active">All</button>
    <button class="category">Necklaces</button>
    <button class="category">Earrings</button>
    <button class="category">Bracelets</button>
    <button class="category">Bangles</button>
  </div>
</section>

<section id="products" class="product-section">
  <div class="product-container">
    <div class="product-card" *ngFor="let product of products; let i=index" [attr.data-category]="product.category"
      [routerLink]="['/product', product.id]">
      <img [src]="'assets/prod-images/'+ product.thumbnail" [alt]="product.name" />
      <h4>{{ product.name }}</h4>
      <p class="price">₹{{ product.price }}</p>

      <div class="card-actions">
        <button class="btn add-cart" (click)="addToCart(product, $event)">Add to Cart</button>
        <button class="btn buy-now">Buy Now</button>
      </div>
    </div>
  </div>

</section>
