// frontend/src/components/Cart.tsx
import React, { useEffect, useState } from 'react';
import { useCart } from '../hooks/useCart';
import './Cart.scss';

const Cart: React.FC = () => {
  const { cartItems, shippingAmount, updateQuantity, removeItem, getSubtotal } = useCart();
  const [subtotal, setSubtotal] = useState<number>(0);
  const [total, setTotal] = useState<number>(0);

  useEffect(() => {
    const newSubtotal = getSubtotal();
    setSubtotal(newSubtotal);
    const shipping = cartItems.length > 0 ? shippingAmount : 0;
    setTotal(newSubtotal + shipping);
  }, [cartItems, shippingAmount, getSubtotal]);

  const handleIncreaseQty = (itemId: number, currentQty: number) => {
    updateQuantity(itemId, currentQty + 1);
  };

  const handleDecreaseQty = (itemId: number, currentQty: number) => {
    if (currentQty > 1) {
      updateQuantity(itemId, currentQty - 1);
    }
  };

  const handleRemoveItem = (itemId: number) => {
    removeItem(itemId);
  };

  return (
    <div className="cart-container">
      <h2 className="cart-title">Your Cart</h2>

      <div className="cart-items">
        {cartItems.map((item) => (
          <div key={item.id} className="cart-item">
            <img
              className="item-image"
              src={`/assets/prod-images/${item.thumbnail}`}
              alt={item.name}
            />

            <div className="item-details">
              <h3 className="item-name">{item.name}</h3>
              <p className="item-price">₹{item.price}</p>

              <div className="quantity-box">
                <button
                  className="qty-btn"
                  onClick={() => handleDecreaseQty(item.id, item.quantity)}
                >
                  -
                </button>
                <input
                  type="text"
                  className="qty-input"
                  value={item.quantity}
                  readOnly
                />
                <button
                  className="qty-btn"
                  onClick={() => handleIncreaseQty(item.id, item.quantity)}
                >
                  +
                </button>
              </div>
            </div>

            <button
              className="remove-btn"
              onClick={() => handleRemoveItem(item.id)}
            >
              ✕
            </button>
          </div>
        ))}
      </div>

      {/* Cart Summary */}
      <div className="cart-summary">
        <div className="summary-row">
          <span>Subtotal</span>
          <span>₹{subtotal}</span>
        </div>

        <div className="summary-row">
          <span>Shipping</span>
          <span>₹{cartItems.length > 0 ? shippingAmount : 0}</span>
        </div>

        <div className="summary-row total">
          <span>Total</span>
          <span>₹{total}</span>
        </div>

        <button className="checkout-btn">Proceed to Checkout</button>
      </div>
    </div>
  );
};

export default Cart;

// frontend/src/app/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { CartService } from '../services/cart.service';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss']
})
export class CartComponent implements OnInit {

  cartItems: any[] = [];
  total = 0;
  shippingAmount = this.cartService.shippingAmount;

  constructor(private cartService: CartService) { }

  ngOnInit(): void {
    this.loadCart();
  }

  loadCart() {
    this.cartItems = this.cartService.getCartItems();
    this.total = this.cartService.getTotal();
  }

  increaseQty(item: any) {
    item.quantity++;
    this.cartService.updateQuantity(item.id, item.quantity);
    this.loadCart();
  }

  decreaseQty(item: any) {
    if (item.quantity > 1) {
      item.quantity--;
      this.cartService.updateQuantity(item.id, item.quantity);
      this.loadCart();
    }
  }

  removeItem(id: number) {
    this.cartService.removeItem(id);
    this.loadCart();
  }
}

<div class="cart-container">

  <h2 class="cart-title">Your Cart</h2>

  <div class="cart-items">

    <div class="cart-item" *ngFor="let item of cartItems">

      <img class="item-image" [src]="'assets/prod-images/' + item.thumbnail">

      <div class="item-details">
        <h3 class="item-name">{{ item.name }}</h3>
        <p class="item-price">₹{{ item.price }}</p>

        <div class="quantity-box">
          <button class="qty-btn" (click)="decreaseQty(item)">-</button>
          <input type="text" class="qty-input" [value]="item.quantity" readonly />
          <button class="qty-btn" (click)="increaseQty(item)">+</button>
        </div>
      </div>

      <button class="remove-btn" (click)="removeItem(item.id)">✕</button>
    </div>


    <!--  <div class="cart-item">
      <img class="item-image" src="assets/prod-images/prod-1/thumbnail.jpg" alt="Product">

      <div class="item-details">
        <h3 class="item-name">Graceful Gold Bangles</h3>
        <p class="item-price">₹1,599</p>

        <div class="quantity-box">
          <button class="qty-btn">-</button>
          <input type="text" class="qty-input" value="1" />
          <button class="qty-btn">+</button>
        </div>
      </div>

      <button class="remove-btn">✕</button>
    </div> -->

    <!--  <div class="cart-item">
      <img class="item-image" src="assets/prod-images/prod-2/thumbnail.jpg" alt="Product">

      <div class="item-details">
        <h3 class="item-name">Royal Pearl Earrings</h3>
        <p class="item-price">₹899</p>

        <div class="quantity-box">
          <button class="qty-btn">-</button>
          <input type="text" class="qty-input" value="1" />
          <button class="qty-btn">+</button>
        </div>
      </div>

      <button class="remove-btn">✕</button>
    </div> -->

  </div>

  <!-- Cart Summary -->
  <div class="cart-summary">
    <div class="summary-row">
      <span>Subtotal</span>
      <span>₹{{ total }}</span>
    </div>

    <div class="summary-row">
      <span>Shipping</span>
      <span>₹{{cartItems.length>0 ? shippingAmount : 0}}</span>
    </div>

    <div class="summary-row total">
      <span>Total</span>
      <span>₹{{ total }}</span>
    </div>

    <button class="checkout-btn">Proceed to Checkout</button>
  </div>

</div>
